arch:
  - arm64
os: linux

dist: jammy

language: shell

services:
  - docker

before_install:
  - docker build -t moussavdb/application-engine-website:latest .
script:
  - docker images moussavdb/application-engine-website
  
after_success:
  - docker login -u="moussavdb" -p="$DOCKER_PASSWORD";
  - docker push moussavdb/application-engine-website:latest;
