
arch:
  - arm64
os: linux
dist: jammy

language: generic

services:
  - docker

before_install:
  - docker build -t moussavdb/application-website-$TRAVIS_CPU_ARCH:latest -t moussavdb/application-website-$TRAVIS_CPU_ARCH:build_$TRAVIS_BUILD_NUMBER .
script:
  - docker images moussavdb/application-website-$TRAVIS_CPU_ARCH
  
after_success:
  - docker login -u="moussavdb" -p="$DOCKER_PASSWORD";
    docker push moussavdb/application-website-$TRAVIS_CPU_ARCH:latest;
    docker push moussavdb/application-website-$TRAVIS_CPU_ARCH:build_$TRAVIS_BUILD_NUMBER;
